// Code generated by SQLBoiler 4.16.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Ingredient     string
	Meal           string
	MealIngredient string
}{
	Ingredient:     "ingredient",
	Meal:           "meal",
	MealIngredient: "meal_ingredient",
}
